#                            ┑(￣▽￣)┍
#              >>>>>>>>>>>>>>>>>>>>>>>>>
#           Fqstalph
#                 Twitter: @fqstalph
#                 Website: github.com/Fqstalph
#               >>>>>>>>>>>>>>>>>>>>>>>>>

Message: "§4§oScreenShare§8 >§c {player} is under ScreenShare"
World: "Hub"

# How does that work?
# The player with the permission ss.cmd can type /ss "player name" and everything will work, 
# the messages you can configure from here
# Small addiction to MultiWorld
